services:
  ai-backend:
    build:
      context: ./ai-backend
    ports:
      - "8000:8000"
  ui-backend:
    build:
      context: ./ui-backend
    ports:
      - "8080:8080"
    depends_on:
      - ai-backend